# Generated by Django 5.2.6 on 2025-09-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='StepUp.in', max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('position', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
