# Generated by Django 5.2.6 on 2025-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_heroslide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(default='Welcome to StepUp.in', max_length=255)),
                ('overview_content', models.TextField(default='Discover the latest trends in footwear with StepUp.in. Shop now for the best deals!')),
                ('next_title', models.CharField(default='Featured Collection', max_length=255)),
                ('bottom_title', models.CharField(default='Explore Our Best Picks', max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='overview_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='overview_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='overview_images/')),
            ],
            options={
                'verbose_name': 'Overview Section',
                'verbose_name_plural': 'Overview Sections',
            },
        ),
    ]
