# Generated by Django 5.2.6 on 2025-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_overviewsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewsection',
            name='image1_title',
            field=models.CharField(default='Mens', max_length=100),
        ),
        migrations.AddField(
            model_name='overviewsection',
            name='image2_title',
            field=models.CharField(default='Womens', max_length=100),
        ),
        migrations.AddField(
            model_name='overviewsection',
            name='image3_title',
            field=models.CharField(default='Kids', max_length=100),
        ),
    ]
