# Generated by Django 5.2.6 on 2025-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_overviewsection_image1_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
