# Generated by Django 5.2.6 on 2025-09-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('style', models.CharField(blank=True, choices=[('Sandals', 'Sandals'), ('Trainers', 'Trainers'), ('Boots', 'Boots'), ('Slippers', 'Slippers'), ('Canvas', 'Canvas'), ('Summer Shop', 'Summer Shop')], max_length=30)),
                ('brand', models.CharField(blank=True, choices=[('Skechers', 'Skechers'), ('Kickers', 'Kickers'), ('Marvel', 'Marvel'), ('Totes', 'Totes'), ('Comfy Steps', 'Comfy Steps'), ('Becket', 'Becket'), ('Lambretta', 'Lambretta')], max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('colors', models.JSONField(default=list)),
                ('image', models.ImageField(upload_to='womenproducts/')),
            ],
        ),
    ]
