# Generated by Django 5.2.6 on 2025-09-20 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_menproduct_mencart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('style', models.CharField(blank=True, choices=[('Sandals', 'Sandals'), ('Trainers', 'Trainers'), ('Boots', 'Boots'), ('Slippers', 'Slippers'), ('Canvas', 'Canvas'), ('School Shoes', 'School Shoes')], max_length=30)),
                ('brand', models.CharField(blank=True, choices=[('Skechers', 'Skechers'), ('Kickers', 'Kickers'), ('Marvel', 'Marvel'), ('Totes', 'Totes'), ('Comfy Steps', 'Comfy Steps'), ('Becket', 'Becket'), ('Lambretta', 'Lambretta')], max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('colors', models.JSONField(default=list)),
                ('image', models.ImageField(upload_to='kidsproducts/')),
            ],
        ),
        migrations.CreateModel(
            name='KidsCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kidsproduct')),
            ],
        ),
    ]
