# Generated by Django 5.2.6 on 2025-09-20 10:11

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_order_account_number_order_bank_name_order_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=products.models.generate_order_number, max_length=12, unique=True),
        ),
    ]
